playerOnJoin: " has joined the server"
playerJoinMOTD: "Plugins in use: Dynmap (roflobster.duckdns.org:8123) , mcMMO, SimpleElevators, RampenDrills, DiscordSRV"
playerOnQuit: " has ragequit"
serverMOTD: "Welcome to my Paper Server!"
